vehicle:
 vehicle_description:
  robotNamespace: hmmwv
  robotName: hmmwv  # NOTE cannot change, will break vehicle.launch because this is hardcoded in
  frameName: map
  ground_truth_topic: base_pose_ground_truth

  # mesh parameters
  scale_factor: 0.2
  mesh_mode: 1

  # vehicle geometry
  base_link: base_link
  base_width: 1.9
  base_length: 3.3
  base_height: 1.2
  base_clearance: 0.5

  # wheels
  wheel_radius: 0.393
  wheel_width: 0.1
  wheel_mass: 2.5
  la: 1.6
  lb: 1.7
  wheel_base: 1
  mu1: 0.9
  mu2: 0.9
  minDepth: 0.005
  kp: 1e8

  # LiDAR properties
  lidar_z: 1.4
  lidar_x: 1.75
  topic: lidar_points

 chrono:
  vehicle_params:
   frict_coeff: 0.9
   rest_coeff: 0.1
   centroidLoc: "[0.056, 0.0, 0.523],"
   centroidOrientation: "[1, 0, 0, 0]"
   chassisMass: "2086.52,"
   chassisInertia: "[1078.52, 2955.66, 3570.20],"
   driverLoc: "[0, 0.5, 1.2],"
   driverOrientation: "[1, 0, 0, 0]"
   motorBlockDirection: "[1, 0, 0],"
   axleDirection: "[0, 1, 0]"
   driveshaftInertia: "0.5,"
   differentialBoxInertia: "0.6"
   conicalGearRatio: "-0.2,"
   differentialRatio: "-1.0"
   forwardGearRatio: " 0.0,"
   reverseGearRatio: "-0.3,"
   maxEngineTorque: "1000.0,"
   maxEngineSpeed: "2000"
   steeringLinkMass: "9.072,"
   steeringLinkInertia: "[1, 1, 1],"
   steeringLinkRadius: "0.03,"
   steeringLinkLength: "0.896"
   pinionRadius: "0.1,"
   pinionMaxAngle: "0.87"
   maxBrakeTorque: "4000"

 common:
  m: 0.0
  Izz: 0.0
  la: 0.0
  lb: 0.0
  wheel_radius: 0.268
